# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: divine curation
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://divinecuration.github.io" # the base hostname & protocol for your site
logo: /assets/img/logo/logo.png
twitter:
  username: divinecuration
  card: summary
github_username:
permalink: /:year/:month/:day/:title:output_ext
# paginate: 10
# paginate_path: "/page:num/"
collections:
  tags:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      author: "Sam"

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
# disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
staticman_url: https://divine-curation-comment-bridge.herokuapp.com/v2/entry/divinecuration/divinecuration.github.io/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LdoRfsUAAAAAKAEZO04fSvw0WyFx0GNyNYSE5_d
  secret: bHgBqhrs+MklX8mMftZAj7r+Gf6m3X9mb5Y7CFvnGfwWHWg/YtfesvmJ9x1w/h6WQUv736O0VwTm0I6OoksoxPXEGEvZXa/bBvZy0rf+cPuGxkZIy946lYgu0vjFwiI1bp3oDmpWPyKICUk+QnBbsQYqLknnUi7kxN6A1wNvH5d7dwo/2Ql6S+QF8Z1mRvSv/rCtv7cPWBJusry180fNx9m9FNy2h+YVGAh6tZIxzwWEAYv7nQlQBbvAUiX7fK/C9q7sQkE9t6lZUMGWihayNDu2nDXDgNsnYZSRprEuYNnMtw55DmomwvUVyojQ5Qx7AdgwMRXUFgWPEeOgT1BCPsad68gJREqEPmRPViNr5N8Q510QGwd8X8iWS/GVmGMyFQQFr815bi20baPHKAFdX8wCYm1wXfqbNa52Z9QsqWdy750Gpy+KxQEowUYBxgyasTuQQ4Yf06flYcT8iF2fiRBapECp94dXIKti+IeGI7RzW29Ysz9dwEYEgP/m/6YVuKSe05kfbpqBphzaii3NTW4Kj0IzuUwYSVgyCJhX4l7O9xvW4JeF7pz4K1tkmy40TncyHEiD1D4a0zij+A2Iymxe77gF0u7gBPxr7EScmeDMGYtfEOexVNrXvs0sAXyHazifipaVlAPChGphPBE5Aci6gfZ6gUn77tREMzT3SdU=
