# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl: ""
title: divine curation
# Whether the header (with large title and subtitle) should be displayed
header: true
# subtitle: A Jekyll theme based on tufte-css
author: Divine Curation
email: divinecuration [at] gmail [dot] com
# description: A Jekyll theme based on tufte-css
logo: /assets/img/logo/logo.png
twitter:
  username: divinecuration
  card: summary
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /:year/:month/:day/:title:output_ext
timezone: Europe/Berlin
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
paginate: 10
git:
  branch: src
plugins:
  - jekyll-paginate
  - jekyll-seo-tag


# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
staticman_url: https://divine-curation-comment-bridge.herokuapp.com/v2/entry/divinecuration/divinecuration.github.io/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LdoRfsUAAAAAKAEZO04fSvw0WyFx0GNyNYSE5_d
  secret: bHgBqhrs+MklX8mMftZAj7r+Gf6m3X9mb5Y7CFvnGfwWHWg/YtfesvmJ9x1w/h6WQUv736O0VwTm0I6OoksoxPXEGEvZXa/bBvZy0rf+cPuGxkZIy946lYgu0vjFwiI1bp3oDmpWPyKICUk+QnBbsQYqLknnUi7kxN6A1wNvH5d7dwo/2Ql6S+QF8Z1mRvSv/rCtv7cPWBJusry180fNx9m9FNy2h+YVGAh6tZIxzwWEAYv7nQlQBbvAUiX7fK/C9q7sQkE9t6lZUMGWihayNDu2nDXDgNsnYZSRprEuYNnMtw55DmomwvUVyojQ5Qx7AdgwMRXUFgWPEeOgT1BCPsad68gJREqEPmRPViNr5N8Q510QGwd8X8iWS/GVmGMyFQQFr815bi20baPHKAFdX8wCYm1wXfqbNa52Z9QsqWdy750Gpy+KxQEowUYBxgyasTuQQ4Yf06flYcT8iF2fiRBapECp94dXIKti+IeGI7RzW29Ysz9dwEYEgP/m/6YVuKSe05kfbpqBphzaii3NTW4Kj0IzuUwYSVgyCJhX4l7O9xvW4JeF7pz4K1tkmy40TncyHEiD1D4a0zij+A2Iymxe77gF0u7gBPxr7EScmeDMGYtfEOexVNrXvs0sAXyHazifipaVlAPChGphPBE5Aci6gfZ6gUn77tREMzT3SdU=
